### ISSUE TITLE
try.redis-db.com fails silently when not accepting Cookies

### ISSUE THREAD

**Issue by NoNoNo** [alexmchale/try.redis#7]
`try.redis-db.com` fails silently when not accepting Cookies.

```
> SET server:name "fido"
"OK"
> GET server:name
null
```

Also `NEXT` does not work.

At least a notice would be nice.

Since it is a single page JS application it should be possible to store the session ID in a local var and send it in-band with the XHR requests?!

Thanks & greetings,
Oliver

**Comment by rubarb** [comment]
+1
